apiVersion: apps/v1
kind: Deployment
metadata: 
  name: braunson-young
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: braunson-young
  template:
    metadata:
      labels:
        app: braunson-young
    spec: 
      containers:
        - name: braunson-young
          image: nginx
          ports: 
          - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 250M
            requests:
              cpu: 50m
              memory: 100M